# Generated by Django 3.1.3 on 2020-11-20 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='bancaria',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='direccion',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='password',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='telefono',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
